# Generated by Django 4.1.1 on 2022-10-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ('sequence_number',)},
        ),
        migrations.CreateModel(
            name='PopularCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='store.category')),
            ],
            options={
                'ordering': ('sequence_number',),
                'abstract': False,
            },
        ),
    ]
