# Generated by Django 4.1.1 on 2022-10-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_recommendation_options_popularcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularcategory',
            options={'verbose_name_plural': 'Popular categories'},
        ),
        migrations.AddField(
            model_name='popularcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
