# Generated by Django 4.1.1 on 2022-10-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_popularcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='popularcategory',
            options={'verbose_name': 'Популярна категорія', 'verbose_name_plural': 'Популярні категорії'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'Рекомендація', 'verbose_name_plural': 'Рекомендації'},
        ),
        migrations.AlterModelOptions(
            name='slideritem',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайди'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазини'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Найменування'),
        ),
    ]
