# Generated by Django 4.1.1 on 2022-09-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_volume_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discount_percentage',
        ),
    ]
