# Generated by Django 4.1.1 on 2022-11-28 08:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name="Ім'я замовника")),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(max_length=250, verbose_name='Коментар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активність')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('street', models.CharField(max_length=255, verbose_name='Вулиця')),
                ('house', models.CharField(max_length=10, verbose_name='Будинок')),
                ('entrance', models.CharField(max_length=10, verbose_name="Під'їзд")),
                ('floor', models.CharField(max_length=5, verbose_name='Поверх')),
                ('flat', models.CharField(max_length=5, verbose_name='Квартири')),
                ('recipient_name', models.CharField(max_length=255, verbose_name="Ім'я отримувача")),
                ('recipient_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону отримувача')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email отримувача')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.CreateModel(
            name='PickUpOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name="Ім'я замовника")),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(max_length=250, verbose_name='Коментар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активність')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.store', verbose_name='Магазин')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
