# Generated by Django 4.1.1 on 2022-11-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_deliveryorder_alter_product_options_pickuporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Коментар'),
        ),
    ]
