# Generated by Django 4.1.1 on 2022-12-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_deliveryorder_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField(verbose_name='Порядковий номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активність')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Популярний продукт',
                'verbose_name_plural': 'Популярні продукти',
            },
        ),
    ]
