# Generated by Django 4.1.1 on 2022-12-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_popularproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopularProducts',
            new_name='PopularProduct',
        ),
    ]
