# Generated by Django 4.1.1 on 2022-12-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_popularproducts_popularproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='payment',
            field=models.CharField(choices=[('cash', 'Оплата готівкою')], default=1, max_length=4, verbose_name='Оплата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='payment',
            field=models.CharField(choices=[('cash', 'Оплата готівкою')], default=1, max_length=4, verbose_name='Оплата'),
            preserve_default=False,
        ),
    ]
