# Generated by Django 4.1.1 on 2022-12-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_deliveryorder_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
        migrations.DeleteModel(
            name='PickUpOrder',
        ),
    ]
