# Generated by Django 4.1.1 on 2022-09-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
