# Generated by Django 4.1.1 on 2022-12-22 14:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_alter_cart_options_alter_cartitem_options'),
        ('store', '0013_delete_deliveryorder_delete_pickuporder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name="Ім'я замовника")),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
                ('payment', models.CharField(choices=[('cash', 'Оплата готівкою')], max_length=4, verbose_name='Оплата')),
                ('comment', models.TextField(blank=True, max_length=250, null=True, verbose_name='Коментар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активність')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.cart', verbose_name='Кошик')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Самовивіз',
                'verbose_name_plural': 'Самовивіз',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name="Ім'я замовника")),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
                ('payment', models.CharField(choices=[('cash', 'Оплата готівкою')], max_length=4, verbose_name='Оплата')),
                ('comment', models.TextField(blank=True, max_length=250, null=True, verbose_name='Коментар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активність')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('street', models.CharField(max_length=255, verbose_name='Вулиця')),
                ('house', models.CharField(max_length=10, verbose_name='Будинок')),
                ('entrance', models.CharField(blank=True, max_length=10, null=True, verbose_name="Під'їзд")),
                ('floor', models.CharField(blank=True, max_length=5, null=True, verbose_name='Поверх')),
                ('flat', models.CharField(blank=True, max_length=5, null=True, verbose_name='Квартири')),
                ('recipient_name', models.CharField(max_length=255, verbose_name="Ім'я отримувача")),
                ('recipient_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону отримувача')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email отримувача')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.cart', verbose_name='Кошик')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
            },
        ),
    ]
